/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-05-06 04:37:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex20200506.*;
import java.util.*;
import java.text.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>점수 총계</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#page {margin:auto; float:center; text-align:center;}\r\n");
      out.write("\t\t#tbl,#ctbl {margin:auto; float:center; text-align:center;}\r\n");
      out.write("\t\tth {background:gray; color:pink;}\r\n");
      out.write("\t\t.row:hover{background:skyblue; color:white;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=page width=1000>\r\n");
      out.write("\t<h1>[강좌별 평균점수]</h1>\r\n");
      out.write("\t<table border=1 width=700 id=tbl>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>강좌번호</th>\r\n");
      out.write("\t\t\t<th>강좌명</th>\r\n");
      out.write("\t\t\t<th>교수명</th>\r\n");
      out.write("\t\t\t<th>강의실</th>\r\n");
      out.write("\t\t\t<th>평균점수</th>\r\n");
      out.write("\t\t\t<th>수강인원</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			EDAO edao=new EDAO();
			ArrayList<CVO> list=edao.clist();
			for(CVO vo:list) {
				out.println("<tr class=row>");
				out.println("<td>" + vo.getLcode() + "</td>");
				out.println("<td>" + vo.getLname() + "</td>");
				out.println("<td>" + vo.getPname() + "</td>");
				out.println("<td>" + vo.getRoom() + "</td>");
				DecimalFormat df=new DecimalFormat("##0.00");
				String strAvg=df.format(vo.getAvg());
				out.println("<td>" + strAvg + "</td>");
				out.println("<td>" + vo.getCount() + "</td>");
				out.println("</tr>");
			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<h1>학생별 평균점수</h1>\r\n");
      out.write("\t<table border=1 width=700 id=tbl>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>학번</th>\r\n");
      out.write("\t\t\t<th>학생명</th>\r\n");
      out.write("\t\t\t<th>학생학과</th>\r\n");
      out.write("\t\t\t<th>평균점수</th>\r\n");
      out.write("\t\t\t<th>수강과목수</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			SDAO sdao=new SDAO();
			ArrayList<SVO> list2=sdao.slist();
			for(SVO vo:list2) {
				out.println("<tr class=row>");
				out.println("<td>" + vo.getScode() + "</td>");
				out.println("<td>" + vo.getSname() + "</td>");
				out.println("<td>" + vo.getSdept() + "</td>");
				DecimalFormat df=new DecimalFormat("##0.00");
				String strAvg=df.format(vo.getAvg());
				out.println("<td>" + strAvg + "</td>");
				out.println("<td>" + vo.getCount() + "</td>");
				out.println("</tr>");
			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\t<h1>제이손~</h1>\r\n");
      out.write("\t\t<table id=\"ctbl\" border=1 width=700></table>\r\n");
      out.write("\t\t<script id=\"ctemp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t<tr class=title>\r\n");
      out.write("\t\t\t\t\t<th>강좌번호</th>\r\n");
      out.write("\t\t\t\t\t<th>강좌명</th>\r\n");
      out.write("\t\t\t\t\t<th>교수명</th>\r\n");
      out.write("\t\t\t\t\t<th>강의실</th>\r\n");
      out.write("\t\t\t\t\t<th>평균점수</th>\r\n");
      out.write("\t\t\t\t\t<th>수강인원</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t{{#each elist}}\r\n");
      out.write("\t\t\t\t<tr class=row>\r\n");
      out.write("\t\t\t\t\t<td class=lcode>{{lcode}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{lname}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{pname}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{room}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{avg}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{count}}</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t{{/each}}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$.ajax({\r\n");
      out.write("\ttype:\"get\",\r\n");
      out.write("\turl:\"ejson.jsp\",\r\n");
      out.write("\tdataType:\"json\",\r\n");
      out.write("\tsuccess:function(data){\r\n");
      out.write("\t\tvar temp=Handlebars.compile($(\"#ctemp\").html());\r\n");
      out.write("\t\t$(\"#ctbl\").html(temp(data));\t\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
