/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-05-06 07:32:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex202005062.*;
import java.util.*;
import java.text.*;

public final class list3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <title>으악2</title>\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("   <script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"student\">\r\n");
      out.write("      <h1>[강좌목록]</h1>\r\n");
      out.write("      <table id=\"tbl\" border=1 width=700></table>\r\n");
      out.write("      <script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>강좌목록</td>\r\n");
      out.write("            <td>강좌명</td>\r\n");
      out.write("            <td>담당교수명</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      {{#each list}}\r\n");
      out.write("         <tr class=row>\r\n");
      out.write("            <td class=lcode>{{lcode}}</td>\r\n");
      out.write("            <td>{{lname}}</td>\r\n");
      out.write("            <td>{{pname}}</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      {{/each}}\r\n");
      out.write("      </script>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"student\">\r\n");
      out.write("      <h1>[수강신청목록]</h1>\r\n");
      out.write("      강좌번호:<span id=\"lcode\"></span>\r\n");
      out.write("       수강신청과목수:<span id=\"cnt\"></span>\r\n");
      out.write("       과목평균:<span id=\"avg\"></span>\r\n");
      out.write("     \r\n");
      out.write("      <table id=\"etbl\" border=1 width=700></table>\r\n");
      out.write("      <script id=\"etemp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>학번</td>\r\n");
      out.write("            <td>학생명</td>\r\n");
      out.write("            <td>점수</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      {{#each elist}}\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>{{scode}}</td>\r\n");
      out.write("            <td>{{sname}}</td>\r\n");
      out.write("            <td>{{grade}}</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      {{/each}}\r\n");
      out.write("      </script>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("   var lcode;\r\n");
      out.write("   var avg;\r\n");
      out.write("   var cnt;\r\n");
      out.write("   \r\n");
      out.write("   getList();\r\n");
      out.write("   //수강신청 목록 출력\r\n");
      out.write("   function getList(){\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type:\"get\",\r\n");
      out.write("         url:\"ajson.jsp\",\r\n");
      out.write("         dataType:\"json\",\r\n");
      out.write("         data:{\"lcode\":lcode},\r\n");
      out.write("         success:function(data){\r\n");
      out.write("            var temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("            $(\"#tbl\").html(temp(data));\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   $(\"#tbl\").on(\"click\", \".row\", function(){\r\n");
      out.write("      lcode=$(this).find(\".lcode\").html();\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type:\"get\",\r\n");
      out.write("         url:\"ajson.jsp\",\r\n");
      out.write("         dataType:\"json\",\r\n");
      out.write("         data:{\"lcode\":lcode},\r\n");
      out.write("         success:function(data){\r\n");
      out.write("            $(\"#lcode\").html(lcode);\r\n");
      out.write("            $(\"#cnt\").html(data.cnt);\r\n");
      out.write("            $(\"#avg\").html(data.avg);\r\n");
      out.write("            var temp=Handlebars.compile($(\"#etemp\").html());\r\n");
      out.write("            $(\"#etbl\").html(temp(data));\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   })\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
