/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-05-01 06:01:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.students;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex20200429.*;
import java.util.*;

public final class list2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>학생목록</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.title {text-align:center; background:gray; color:white;}\r\n");
      out.write("\t\t.row {text-align:center;}\r\n");
      out.write("\t\t.row:hover {background:skyblue; color:white; cursor:pointer;}\r\n");
      out.write("\t\t#slist, #clist {display:none;}\r\n");
      out.write("\t\tbutton {cursor:pointer;}\r\n");
      out.write("\t\t#students {width:680px; background:gray; color:white; padding:10px; display:none;}\r\n");
      out.write("\t\t#courses {width:680px; background:gray; color:white; padding:10px; margin-top:10px;display:none;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<a href=\"/ex20200429/professors/list.jsp\">교수관리</a>\r\n");
      out.write("\t\t<a href=\"/ex20200429/students/list2.jsp\">학생관리</a>\r\n");
      out.write("\t\t<a href=\"/ex20200429/courses/clist.jsp\">강좌관리</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<h1>[학생목록]</h1>\r\n");
      out.write("\t<table border=1 width=700 id=\"tbl\">\r\n");
      out.write("\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t<td>학번</td>\r\n");
      out.write("\t\t\t<td>학생명</td>\r\n");
      out.write("\t\t\t<td>학과</td>\r\n");
      out.write("\t\t\t<td>생년월일</td>\r\n");
      out.write("\t\t\t<td>지도교수</td>\r\n");
      out.write("\t\t\t<td>수강신청</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
	
			SDAO sdao=new SDAO();
			ArrayList<SVO> list=sdao.list("%%");
			for(SVO vo:list) {
				out.println("<tr class=row>");
				out.println("<td class=scode>" + vo.getScode() + "</td>");
				out.println("<td class=sname>" + vo.getSname() + "</td>");
				out.println("<td>" + vo.getSdept() + "</td>");	
				out.println("<td>" + vo.getBirthday() + "</td>");
				out.println("<td>" + vo.getAdvisor() + "</td>");
				out.println("<td><button>수강신청</button></td>");
				out.println("</tr>");
			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"enroll\">\r\n");
      out.write("\t\t<h1>수강신청목록</h1>\r\n");
      out.write("\t\t<div id=students>\r\n");
      out.write("\t\t\t학번 : <span id=\"scode\"></span>\r\n");
      out.write("\t\t\t성명 : <span id=\"sname\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"courses\">\r\n");
      out.write("\t\t\t강좌명 : \r\n");
      out.write("\t\t\t<select id=\"lcode\"></select>\r\n");
      out.write("\t\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t{{#each clist}}\r\n");
      out.write("\t\t\t\t<option value={{lcode}}>{{lcode}}:{{lname}}</option>\r\n");
      out.write("\t\t\t{{/each}}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"신청\" id=\"btnEnroll\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table id=\"etbl\" border=1 width=700></table>\r\n");
      out.write("\t\t<script id=\"temp2\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t<tr class=title>\r\n");
      out.write("\t\t\t\t\t<td>강좌코드</td>\r\n");
      out.write("\t\t\t\t\t<td>강좌이름</td>\r\n");
      out.write("\t\t\t\t\t<td>수강신청일</td>\r\n");
      out.write("\t\t\t\t\t<td>점수</td>\r\n");
      out.write("\t\t\t\t\t<td>수강취소</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t{{#each elist}}\r\n");
      out.write("\t\t\t\t<tr class=row>\r\n");
      out.write("\t\t\t\t\t<td class=lcode>{{lcode}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{lname}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{edate}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{grade}}</td>\r\n");
      out.write("\t\t\t\t\t<td><button>수강취소</button</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t{{/each}}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar scode;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row button\", function(){\r\n");
      out.write("\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\tscode=row.find(\".scode\").html();\r\n");
      out.write("\t\tvar sname=row.find(\".sname\").html();\r\n");
      out.write("\t\t$(\"#scode\").html(scode);\r\n");
      out.write("\t\t$(\"#sname\").html(sname);\r\n");
      out.write("\t\t$(\"#students\").show();\r\n");
      out.write("\t\t$(\"#courses\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetlist();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"cjson.jsp\",\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t$(\"#lcode\").html(temp(data));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getlist(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"ejson.jsp\",\r\n");
      out.write("\t\t\tdata:{\"scode\" : scode},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar temp=Handlebars.compile($(\"#temp2\").html());\r\n");
      out.write("\t\t\t\t$(\"#etbl\").html(temp(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnEnroll\").on(\"click\", function(){\r\n");
      out.write("\t\tif(confirm(\"수강신청을 하시겠습니까?\")==false) return;\r\n");
      out.write("\t\tvar lcode=$(\"#lcode\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"insert.jsp\",\r\n");
      out.write("\t\t\tdata:{\"lcode\":lcode, \"scode\":scode},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"수강신청완료!\");\r\n");
      out.write("\t\t\t\tgetlist();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#etbl\").on(\"click\", \".row button\",function(){\r\n");
      out.write("\t\tif(confirm(\"수강취소 하시겠습니까?\")==false) return;\r\n");
      out.write("\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\tvar lcode=row.find(\".lcode\").html();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"delete.jsp\",\r\n");
      out.write("\t\t\tdata:{\"lcode\": lcode, \"scode\":scode},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"취소되었다\");\r\n");
      out.write("\t\t\t\tgetlist();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
