/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-05-05 06:57:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex01.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>강좌별 평균점수</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#page {margin:auto; width:1000px; text-align:center; border:2px solid black; border-radius:10px;}\r\n");
      out.write("\t\t#tbl, #ctbl {margin:auto; margin-bottom:30px;}\r\n");
      out.write("\t\tth {background:gray; color:white;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=page>\r\n");
      out.write("\t<h1>[평균점수]</h1>\r\n");
      out.write("\t<h1>서블릿</h1>\r\n");
      out.write("\t<table border=1 width=700 id=\"tbl\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t<th>강좌코드</th>\r\n");
      out.write("\t\t\t<th>강좌명</th>\r\n");
      out.write("\t\t\t<th>교수명</th>\r\n");
      out.write("\t\t\t<th>평균점수</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
	
			EnrollDAO dao=new EnrollDAO();
			ArrayList<EnrollVO> list=dao.clist();
			for(EnrollVO vo:list) {
				out.println("<tr class=title>");
				out.println("<td>" + vo.getLcode() + "</td>");
				out.println("<td>" + vo.getLname() + "</td>");
				out.println("<td>" + vo.getPname() + "</td>");
				out.println("<td>" + vo.getAvg() + "</td>");
				out.println("</tr>");
			}
			
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\t<h1>핸들바</h1>\r\n");
      out.write("\t\t<table id=\"ctbl\" border=1 width=700></table>\r\n");
      out.write("\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t<tr class=title>\r\n");
      out.write("\t\t\t\t\t<th>강좌코드</th>\r\n");
      out.write("\t\t\t\t\t<th>강좌이름</th>\r\n");
      out.write("\t\t\t\t\t<th>교수명</th>\r\n");
      out.write("\t\t\t\t\t<th>평균점수</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t{{#each clist}}\r\n");
      out.write("\t\t\t\t<tr class=row>\r\n");
      out.write("\t\t\t\t\t<td class=lcode>{{lcode}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{lname}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{pname}}</td>\r\n");
      out.write("\t\t\t\t\t<td>{{avg}}</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t{{/each}}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"json.jsp\",\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t$(\"#ctbl\").html(temp(data));\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
