/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-04-19 06:00:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex01.*;
import java.util.*;
import java.sql.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script> \r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t*{font-family:\"배달의민족 주아\";}\r\n");
      out.write("\t\th1,h3 {text-align:center;}\r\n");
      out.write("\t\t#content {width:700px; background:#9aa6a2; color:white; margin:auto; padding:10px;}\r\n");
      out.write("\t\t#tbl {margin:auto;}\r\n");
      out.write("\t\ttd{text-align:center;}\r\n");
      out.write("\t\t.kor, .eng, .mat {text-align:right;}\r\n");
      out.write("\t\t.row {color:black;}\r\n");
      out.write("\t\tbody {background:#fffff3;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>[성적처리]</h1>\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t이름 : <input type=\"text\" id=\"txtname\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t국어 : <input type=\"text\" id=\"txtkor\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t영어 : <input type=\"text\" id=\"txteng\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t수학 : <input type=\"text\" id=\"txtmat\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<input type=\"button\" value=\"등록\" id=\"btninsert\">\r\n");
      out.write("\t\t<h3>[성적목록]</h3>\r\n");
      out.write("\t\t<table border=1 width=650 id=\"tbl\">\r\n");
      out.write("\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t<th>NO.</th>\r\n");
      out.write("\t\t\t\t<th>name</th>\r\n");
      out.write("\t\t\t\t<th>국어점수</th>\r\n");
      out.write("\t\t\t\t<th>영어점수</th>\r\n");
      out.write("\t\t\t\t<th>수학점수</th>\r\n");
      out.write("\t\t\t\t<th>수정</th>\r\n");
      out.write("\t\t\t\t<th>삭제</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				GradeDAO dao=new GradeDAO();
				ArrayList<GradeVO> list=dao.list();
				for(int i=0; i<list.size(); i++) {
					GradeVO vo=list.get(i);
					int gno=vo.getGno();
					String gname=vo.getGname();
					int kor=vo.getKor();
					int eng=vo.getEng();
					int mat=vo.getMat();
					out.print("<tr class=row>");
					out.print("<td class=gno>" + gno + "</td>");
					out.print("<td class=gname>" + gname + "</td>");
					out.print("<td><input type=text class=kor size=4 value=" + kor + "></td>");
					out.print("<td><input type=text class=eng size=4 value=" + eng + "></td>");
					out.print("<td><input type=text class=mat size=4 value=" + mat + "></td>");
					out.print("<td><button class='update'>수정</button></td>");
					out.print("<td><button class='delete'>삭제</button></td>");
					out.print("</tr>");
				}
			
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"#btninsert\").on(\"click\", function(){\r\n");
      out.write("\t\tif(confirm(\"등록하시겠습니까?\")==false) return;\r\n");
      out.write("\t\tvar gname=$(\"#txtname\").val();\r\n");
      out.write("\t\tvar kor=$(\"#txtkor\").val();\r\n");
      out.write("\t\tvar eng=$(\"#txteng\").val();\r\n");
      out.write("\t\tvar mat=$(\"#txtmat\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(gname==\"\"){\r\n");
      out.write("            alert(\"이름을 입력하세요!\");\r\n");
      out.write("            $(\"#txtname\").val(\"\");\r\n");
      out.write("            $(\"#txtname\").focus();\r\n");
      out.write("         }else if(kor==\"\"|| kor.replace(/[0-9]/g,'')){\r\n");
      out.write("            alert(\"국어점수를 숫자로 입력하세요!\");\r\n");
      out.write("            $(\"#txtkor\").val(\"\");\r\n");
      out.write("            $(\"#txtkor\").focus();\r\n");
      out.write("         }else if(eng==\"\"|| eng.replace(/[0-9]/g,'')){\r\n");
      out.write("            alert(\"영어점수를 숫자로 입력하세요!\");\r\n");
      out.write("            $(\"#txteng\").val(\"\");\r\n");
      out.write("            $(\"#txteng\").focus();\r\n");
      out.write("         }else if(mat==\"\"|| mat.replace(/[0-9]/g,'')){\r\n");
      out.write("            alert(\"수학점수를 숫자로 입력하세요!\");\r\n");
      out.write("            $(\"#txtmat\").val(\"\");\r\n");
      out.write("            $(\"#txtmat\").focus();\r\n");
      out.write("         }else{\r\n");
      out.write("            location.href=\"sqlinsert.jsp?gname=\"+gname+\"&kor=\"+kor+\"&eng=\"+eng+\"&mat=\"+mat;\r\n");
      out.write("         }\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row .delete\", function(){\r\n");
      out.write("\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\tvar gno=row.find(\".gno\").html();\r\n");
      out.write("\t\r\n");
      out.write("\t\tif(confirm(gno+\"번을 삭제하시겠습니까?\")==false) return;\r\n");
      out.write("\t\t\tlocation.href=\"sqldelete.jsp?gno=\"+gno;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row .update\", function(){\r\n");
      out.write("\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\tvar gno=row.find(\".gno\").html();\r\n");
      out.write("\t\tvar kor=row.find(\".kor\").val();\r\n");
      out.write("\t\tvar eng=row.find(\".eng\").val();\r\n");
      out.write("\t\tvar mat=row.find(\".mat\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t\tif(confirm(gno+\"번을 수정하시겠습니까?\")==false) return;\r\n");
      out.write("\t\tlocation.href=\"sqlupdate.jsp?gno=\"+gno+\"&kor=\"+kor+\"&eng=\"+eng+\"&mat=\"+mat;\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
