/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-04-18 12:18:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex01.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String strBno=request.getParameter("bno"); //몇번째 프라이머리 키의 다른 스키마 튜플들을 불러올지 알아야함으로 bno를 리쿼스트를 함
	int bno=Integer.parseInt(strBno);	//VO클래스에 getBno메서드는 애초에 인트값을 받는걸로 만들어서 타입변환을 해야만 메서드를 사용 가능함
	BBSDAO dao=new BBSDAO(); //dao클래스 연결
	BBSVO vo=dao.read(bno); //vo클래스에 dao클래스의 리드 메서드로 치환하는데 그 값은 리퀘스트에서 가져온 bno값임

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>글읽기</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>글읽기</h1>\r\n");
      out.write("\t<a href=\"list.jsp\">목록</a>\r\n");
      out.write("\t<form action=\"sqlUpdate.jsp\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"bno\" value=\"");
      out.print(bno);
      out.write("\"> <!-- 삭제버튼을 눌렀을때 실행될 jsp에서 몇번째 프라이머리 키의 값을 삭제할지 알아야해서 불러오긴 하나 보여줄 필요가 없음으로 출력방식이 히든이다, 그러므로 bno값은 리퀘스트에서 온 값이다 -->\r\n");
      out.write("\t\t제목: <input type=\"text\" name=\"title\" value=\"");
      out.print( vo.getTitle() );
      out.write("\"> <!-- vo에 저장된 dao.read(bno)에 저장된 값을 불러오기위해 사용함 -->\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t내용: <textarea rows=\"5\" cols=\"50\" name=\"content\">");
      out.print( vo.getContent() );
      out.write("</textarea> <!-- vo에 저장된 dao.read(bno)에 저장된 값을 불러오기위해 사용함 -->\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"수정\">\r\n");
      out.write("\t\t<input type=\"reset\" value=\"취소\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"삭제\" onClick=\"location.href='sqlDelete.jsp?bno=");
      out.print( vo.getBno() );
      out.write("'\"> <!-- =은 프린트와 같다는 뜻임 , 삭제할 글 번호에 맞는 값을 불러오기 위함임 -->\r\n");
      out.write("\t\t<input type=\"button\" value=\"목록\" onClick=\"location.href='list.jsp'\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
