/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-04-19 11:19:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex02.*;
import java.util.*;
import java.sql.*;
import java.util.Date;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>댓글관리</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#page {background:gray; width:1000px; margin:auto; padding:10px; text-align:center;}\r\n");
      out.write("\t\th1 {text-align:center;}\r\n");
      out.write("\t\t.box{width:700px; border:1px solid black; padding:10px; text-align:center; margin:auto;}\r\n");
      out.write("\t\t.date {width:300px; font-size:20px; color:black; text-align:left;}\r\n");
      out.write("\t\t#heart {float:right;}\r\n");
      out.write("\t\t.content{padding:10px; font-size:15px; background:white;}\r\n");
      out.write("\t\t.cnt {font-size:12px; color:red; text-align:right;}\r\n");
      out.write("\t\t.title {overflow:hidden;}\r\n");
      out.write("\t\t#btninsert {float:center;}\r\n");
      out.write("\t\t.like {text-align:right;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t<h1>[댓글관리]</h1>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=content size=90>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"저장\" id=btninsert>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t");

	ReplyDAO dao=new ReplyDAO();
	ArrayList<ReplyVO> list=dao.list();
	for(int i=0; i<list.size(); i++) {
		ReplyVO vo=list.get(i);
		
		int rno=vo.getRno();
		String content=vo.getContent();
		Date wdate=vo.getWdate();
		int cnt=vo.getCnt();
		
		out.println("<div class=box>");
        out.println("<div class=title>");
        out.println("<div class=like rno=" + rno + ">");
        out.println("<button class=delete style=color:red>X</button>");
        out.println("<button class=update style=color:red>♥</button>");
        out.println("<span class='cnt'>" + cnt + "</span>");
        out.println("</div>");
        out.println("<div class=date>" + wdate + "</div>");
        out.println("</div>");
        out.println("<div class=content>");
        out.println(content);
        out.println("</div>");
        out.println("</div>");
		
	}
	
	
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\".box\").on(\"click\" , \".delete\", function(){\r\n");
      out.write("\t\tvar rno=$(this).parent().attr(\"rno\");\r\n");
      out.write("\t\tif(confirm(rno + \"번을 삭제하시겠습니까?\")==false) return;\r\n");
      out.write("\t\tlocation.href=\"sqldelete.jsp?rno=\"+rno;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".box\").on(\"click\" , \".update\" , function(){\r\n");
      out.write("\t\tvar rno=$(this).parent().attr(\"rno\");\r\n");
      out.write("\t\tif(confirm(rno+\"번을 좋아요! 하실래요?\")==false) return;\r\n");
      out.write("\t\tlocation.href=\"sqlupdate.jsp?rno=\"+rno;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btninsert\").on(\"click\" , function(){\r\n");
      out.write("\t\tif(confirm(\"댓글을 저장하시겠습니까?\")==false) return;\r\n");
      out.write("\t\tvar content=$(\"#content\").val();\r\n");
      out.write("\t\tif(content==\"\"){\r\n");
      out.write("\t\t\talert(\"내용을 입력하세요.\")\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tlocation.href=\"sqlinsert.jsp?content=\"+content;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
